---
# handlers file for ansible-samba
- name: restart nmbd
  service:
    name: nmbd
    state: restarted
  become: true
- name: restart smbd
  service:
    name: smbd
    state: restarted
  become: true

